//! Writer — takes generated WikiPages and writes them to `.ide/repowiki/`
//! with the correct directory structure.

use super::{RepoWikiConfig, WikiPage};
use std::path::PathBuf;

/// Write all wiki pages to the output directory
pub fn write_wiki(pages: &[WikiPage], config: &RepoWikiConfig) -> Result<(), String> {
    let output_root = config.project_path.join(&config.output_dir);

    // Ensure output directory exists
    std::fs::create_dir_all(&output_root)
        .map_err(|e| format!("Cannot create output dir {:?}: {}", output_root, e))?;

    // Write each page
    for page in pages {
        let page_path = output_root.join(&page.rel_path);

        // Ensure parent directory exists (for nested pages like 03-core-concepts/foo.md)
        if let Some(parent) = page_path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("Cannot create dir {:?}: {}", parent, e))?;
        }

        std::fs::write(&page_path, &page.content)
            .map_err(|e| format!("Cannot write {:?}: {}", page_path, e))?;

        log::info!("Wrote wiki page: {:?}", page_path);
    }

    // Write a README.md index at the root
    write_index(&output_root, pages)?;

    // Write a .gitignore if it doesn't already exist (suggest keeping wiki in git)
    let gitignore_path = output_root.join(".gitignore");
    if !gitignore_path.exists() {
        std::fs::write(&gitignore_path, "# RepoWiki output — optionally gitignore\n# Remove this file to track wiki in version control\n")
            .map_err(|e| format!("Cannot write .gitignore: {}", e))?;
    }

    Ok(())
}

/// Write a README.md index listing all pages
fn write_index(output_root: &PathBuf, pages: &[WikiPage]) -> Result<(), String> {
    let mut content = String::from(
        "# RepoWiki\n\n\
         Auto-generated documentation for this project.\n\n\
         > Generated by [Kyro IDE](https://github.com/nkpendyam/Kyro_IDE) RepoWiki engine.\n\n\
         ## Pages\n\n",
    );

    for page in pages {
        content.push_str(&format!("- [{}]({})\n", page.title, page.rel_path));
    }

    content.push_str(&format!(
        "\n---\n\n*Last generated: {}*\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
    ));

    let readme_path = output_root.join("README.md");
    std::fs::write(&readme_path, content).map_err(|e| format!("Cannot write README.md: {}", e))?;

    Ok(())
}

/// Remove the entire repowiki output directory
pub fn clean_wiki(config: &RepoWikiConfig) -> Result<(), String> {
    let output_root = config.project_path.join(&config.output_dir);
    if output_root.exists() {
        std::fs::remove_dir_all(&output_root)
            .map_err(|e| format!("Cannot remove {:?}: {}", output_root, e))?;
    }
    Ok(())
}
